---
title: "ECMO Chart Review"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#To Dos and questions
```{r}
#2. Chart review
#2.1 Check all patients with "NA" in "ROSC erreicht" variable if reanimaton is 1 or 2
#2.2 check cases with "unclear" or missing ECMO
#2.3 check "unclear" or missing Impella
#2.4 check patients with missing mortality
#2.5 check patients who have ROSC if they really had ROSC

Chart review of final cohort (N = 93): ALWAYS create NEW Variable which can be merged into main dataset by id
  #Done:1. All missing values of already existing variables (see Table)
  #Done: 2. Create provider variable: prov1_t1, prov2_t1, prov3_t1, prov1_t2, prov2_t2, prov3_t2

5. Get ECMO and ECMELLA data for most recent patients - send request to Kalinowksy --> create a new google sheet (new tab) with exactly the same column names
```

#Load libraries

```{r}
library(dplyr)
library(summarytools)
library(tidyverse)
library(DescTools)
library(knitr)
library(kableExtra)
library(tableone)
library(pander)
library(sjPlot)
library(broom)
library(rms)
library(Hmisc)
library(sjPlot)
library(sjmisc)
library(sjlabelled)
library("DiagrammeR")
library(naniar)
library(ivprobit)
library(ggpubr)
panderOptions('table.split.table', Inf)
```

#Import data

```{r}
#Import data
## convert the following variables to date before importing: kopiertes datum, ecmo einbau/ausbau, impella einbau/ausbau, krankenhaus aufnahme/entlassung, ITS aufnahme/entlassung, sterbetag
## convert to numeric: both EF variables

#all
library(readxl)
ecmo_all_campi <- read_excel("ecmo_data1_all_campi.xlsx", 
    col_types = c("numeric", "numeric", "date", 
        "text", "text", "numeric", "text", 
        "text", "date", "date", "text", "text", 
        "date", "date", "text", "text", "date", 
        "date", "date", "date", "date", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "numeric", "numeric", "text", 
        "text"))
View(ecmo_all_campi)


#CBF 2016-2019

library(readxl)
ecmo_cbf_2016_2019 <- read_excel("ecmo_data1_cbf_2016_2019.xlsx", 
    col_types = c("numeric", "numeric", "date", 
        "text", "numeric", "numeric", "text", 
        "text", "date", "date", "text", "text", 
        "date", "date", "text", "text", "date", 
        "date", "date", "date", "date", "text", 
        "text", "text", "text", "text", "text", 
        "text", "numeric", "numeric", "text"))
View(ecmo_cbf_2016_2019)


#CBF 2013-2015

library(readxl)
ecmo_cbf_2013_2015 <- read_excel("ecmo_data1_cbf_2013_2015.xlsx", 
    col_types = c("numeric", "numeric", "date", 
        "numeric", "numeric", "text", "text", 
        "text", "date", "date", "numeric", 
        "text", "date", "date", "text", "text", 
        "date", "date", "date", "date", "date", 
        "numeric", "text", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "text"))
View(ecmo_cbf_2013_2015)

#CCM 2016-2019

library(readxl)
ecmo_ccm_2016_2019 <- read_excel("ecmo_data1_ccm_2016_2019.xlsx", 
    col_types = c("numeric", "text", "date", 
        "text", "text", "numeric", "text", 
        "text", "date", "date", "text", "text", 
        "date", "date", "text", "text", "date", 
        "date", "date", "date", "date", "numeric", 
        "text", "text", "text", "text", "text", 
        "text", "numeric", "numeric", "text"))
View(ecmo_ccm_2016_2019)
```

#merge to one master dataset

```{r}
ecmo_all_campi2 <- ecmo_all_campi %>% select(!"...32") #remove column on the right

#append all datasets
ecmo_master1 <- rbind(ecmo_all_campi2, ecmo_cbf_2013_2015, ecmo_cbf_2016_2019, ecmo_ccm_2016_2019)

#drop duplicates
ecmo_mis <- which(!complete.cases(ecmo_master1$`ECMO ja/nein`)) #please control if this is a correct way to identify those duplicate patients
ecmo_master2 <- ecmo_master1[c(-ecmo_mis), ]

#why so many missings? check which patients were dropped


#drop patients with protected PCI
ecmo_master2 <- ecmo_master2 %>% mutate(ppci = case_when((`Kommentar ECMO` == "PCI unter ECMO-Schutz" |
                                                           `Kommentar ECMO` == "PCI unter ECMOSchutz" |
                                                            `Kommentar ECMO` == "PCI unter ECMO-Support" |
                                                            `Kommentar ECMO` == "PCI unter ECMO Unterstützung  bei TAVI" |
                                                            `Kommentar Impella` == "PCI unter Impellaschutz" |
                                                            `Kommentar Impella` == "PCI unter Impellaschutz?" |
                                                            `Kommentar Impella` == "PCI unter PHP-Schutz" |
                                                            `Kommentar Impella` == "PCI mit Impellaschutz" |
                                                            `Kommentar Impella` == "PCI unter  Impellschutz" |
                                                            `Kommentar Impella` == "PCI unter Impellaschutz, unklar im AB" |
                                                             `Kommentar Impella` == "keine Erwähnung Impella, ist nur die Rede von PCI unter PHP-Schutz" |
                                                            
                                                            `Kommentar Impella` == "PCI unter Impellaschutz - aber 1 Tag länger belassen"
                                                          ) ~ 1))
ecmo_master2$ppci[is.na(ecmo_master2$ppci)] <- 0

#please check if we included all protected PCIs with the text above

ecmo_master3 <- ecmo_master2 %>% filter(ppci == 0)

#several patients without diagnoses - please check
```


#crete clean variables

```{r}
#campus

count(ecmo_master3, `Aus welcher Klinik`)

ecmo_master3 <- ecmo_master3 %>% mutate(campus = case_when(
  `Aus welcher Klinik` == "CBF" ~ 'cbf',
  `Aus welcher Klinik` == "CCM/CBF" ~ 'cbf',
  `Aus welcher Klinik` == "CVK/CBF" ~ 'cbf',
  `Aus welcher Klinik` == "CCM" ~ 'ccm',
   `Aus welcher Klinik` == "CVK" ~ 'cvk'))

campus <- ggplot(ecmo_master3, aes(x="", y= "", fill=campus)) +
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()


#ECMO yes/no character (patient could also have had impella!)

count(ecmo_master3, `ECMO ja/nein`)

ecmo_master3 <- ecmo_master3  %>% mutate(ecmo = case_when(
  `ECMO ja/nein` == "ja" ~ "VA-ECMO",
  `ECMO ja/nein` == "nein" ~ "No ECMO",
  `ECMO ja/nein` == "vv-ECMO" ~ "VV-ECMO",
  `ECMO ja/nein` == "HLM während TAVI?" ~ "Unclear",
   `ECMO ja/nein` == "keine Doku zur Ecmo?" ~ "Unclear"))

#ECMO yes/no numeric

ecmo_master3 <- ecmo_master3  %>% mutate(ecmo_num = case_when(
  `ECMO ja/nein` == "ja" ~ "1",
  `ECMO ja/nein` == "nein" ~ "0",
  `ECMO ja/nein` == "vv-ECMO" ~ "2",
  `ECMO ja/nein` == "HLM während TAVI?" ~ ".",
   `ECMO ja/nein` == "keine Doku zur Ecmo?" ~ "."))
ecmo_master3$ecmo_num <- as.numeric(ecmo_master3$ecmo_num )

ecmo <- ggplot(ecmo_master3, aes(x="", y= "", fill=ecmo)) +
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()

#Impella yes/no character

count(ecmo_master3, `Impella ja/nein`)

ecmo_master3 <- ecmo_master3  %>% mutate(impella = case_when(
  `Impella ja/nein` == "?" ~ "unclear",
  `Impella ja/nein` == "43249" ~ "unclear",
  `Impella ja/nein` == "aj" ~ "LV impella",
  `Impella ja/nein` == "ja" ~ "LV impella",
   `Impella ja/nein` == "nein" ~ "No impella",
  `Impella ja/nein` == "RV-Impella" ~ "RV impella",))

#Impella yes/no numeric

ecmo_master3 <- ecmo_master3  %>% mutate(impella_num = case_when(
  `Impella ja/nein` == "?" ~ ".",
  `Impella ja/nein` == "43249" ~ ".",
  `Impella ja/nein` == "aj" ~ "1",
  `Impella ja/nein` == "ja" ~ "1",
   `Impella ja/nein` == "nein" ~ "0",
  `Impella ja/nein` == "RV-Impella" ~ "2",))
ecmo_master3$impella_num <- as.numeric(ecmo_master3$impella_num )


impella <- ggplot(ecmo_master3, aes(x="", y= "", fill=impella)) +
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()


#ECMELLA yes/no

##only date
ecmo_master3$ecmo_implantation <- as.Date(ecmo_master3$`ECMO wann eingebaut?`)
ecmo_master3$impella_implantation <- as.Date(ecmo_master3$`Impella wann eingebaut?`)

##1. was impella implantation during ecmo ?

ecmo_master3$ecmo_interval <- interval(ecmo_master3$ecmo_implantation, ecmo_master3$`ECMO wann ausgebaut?`) #create time interval
ecmo_master3$impella_during_ecmo <- ecmo_master3$impella_implantation %within% ecmo_master3$ecmo_interval #test if impella implantation was during ecmo 
n <- ecmo_master3 %>% select(`ECMO wann eingebaut?`, `ECMO wann ausgebaut?`, `Impella wann eingebaut?`, impella_during_ecmo) #check manually

##see how many test negative and why 
n <- ecmo_master3 %>% filter(impella_during_ecmo==F)

##2. was ecmo implantation during impella? same procedure

ecmo_master3$impella_interval <- interval(ecmo_master3$impella_implantation, ecmo_master3$`Impella wann ausgebaut?`) #create time interval
ecmo_master3$ecmo_during_impella <- ecmo_master3$ecmo_implantation %within% ecmo_master3$impella_interval

n <- ecmo_master3 %>% select(`Impella wann eingebaut?`, `Impella wann ausgebaut?`, `ECMO wann eingebaut?`, ecmo_during_impella) #check manually

##3. create variable that covers both 
ecmo_master3$ecmella_true <- ifelse(ecmo_master3$ecmo_during_impella==T | ecmo_master3$impella_during_ecmo==T, 
                                    TRUE, FALSE)

##check patients that are exlucded
n <- ecmo_master3 %>% filter(ecmella_true==F)

##final ecmella definition --> make sure only VA-ECMO and LV-Impella are included in variable
ecmo_master3$ecmella_final <- ifelse(ecmo_master3$ecmella_true==T & ecmo_master3$ecmo=="VA-ECMO" & ecmo_master3$impella=="LV impella", 
                                     TRUE, FALSE)
count(ecmo_master3, ecmella_final)

ecmo_master3$ecmella_num <- ifelse(ecmo_master3$ecmella_final==T, 1, 0)

n <- ecmo_master3 %>% filter(ecmella_true==T & ecmella_final==F)


##intervention variable
ecmo_master3$intervention <- ifelse(ecmo_master3$ecmella_final==TRUE, "ECMELLA",
                                    ifelse(ecmo_master3$ecmo=="VA-ECMO", "VA-ECMO",
                                       ifelse(ecmo_master3$impella=="LV impella", "LV-Impella", 
                                                  "others")))
##test if code worked appropriately 
n <- ecmo_master3 %>% filter(intervention=="others")
##patients with intervention = unclear have a vv ecmo or rv impella or nothing at all 

n <- ecmo_master3 %>% filter(intervention=="LV-Impella")
## patients with intervention =LV-Impella have a LV-Impella and no ECmo or a vv-ecmo

n <- ecmo_master3 %>% filter(intervention=="VA-ECMO")
##patients with intervention=va-ecmo have a va ecmo and no impella OR both but not simultaneously 



#ECMELLA vs. ECMO variable

ecmo_master3 <- ecmo_master3 %>% mutate(trt = case_when(intervention == "ECMELLA" ~ 1,
                                  intervention == "VA-ECMO" ~ 0))
ecmo_master3$trt <- as.numeric(ecmo_master3$trt)



#mortality

ecmo_master3$mort <- as.character(ecmo_master3$`Sterbezeit (0 = nicht tot)`)
ecmo_master3$mort[ecmo_master3$mort == "1899-12-31 00:00:00"] <- 0
ecmo_master3$mort[!(ecmo_master3$mort == 0)] <- 1
ecmo_master3$mort <- as.numeric(ecmo_master3$mort)
ecmo_master3$mort <- as.logical(ecmo_master3$mort)

n <- ecmo_master3 %>% select(`Sterbezeit (0 = nicht tot)`, mort)

#rea

count(ecmo_master3, `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)`)

ecmo_master3 <- ecmo_master3  %>% mutate(rea = case_when(
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "0" ~ "No rea",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "?" ~ "unclear",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "0 (Kardioversion bei VT)" ~ "No rea",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "0.0" ~ "No rea",
   `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "1" ~ "Out-of-hospital",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "1.0" ~ "Out-of-hospital",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "2" ~ "In-hospital",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "2.0" ~ "In-hospital",
  `Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)` == "2 beim Ausladen aus dem Krankenwagen " ~ "In-hospital",))
#check cases with missings and "unclear"
n <- ecmo_master3 %>% select(`Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)`, rea)


rea <- ggplot(ecmo_master3, aes(x="", y= "", fill=rea)) +
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()



#years

ecmo_master3$year <- as.character(ecmo_master3$`Krankenhaus - Aufnahmezeit`)
ecmo_master3$year <- substr(ecmo_master3$year, 1, 4)

year_ecmo <- ggplot(data = ecmo_master3, aes(x = year, y = ecmo_num, fill= campus)) +
    geom_bar(stat="identity")

year_impella <- ggplot(data = ecmo_master3, aes(x = year, y = impella_num, fill= campus)) +
    geom_bar(stat="identity")

year_ecmo_type <- ggplot(data = ecmo_master3, aes(x = year, y = ecmo_num, fill= ecmo)) +
    geom_bar(stat="identity")

year_ecmo_rea <- ggplot(data = ecmo_master3, aes(x = year, y = ecmo_num, fill= rea)) +
    geom_bar(stat="identity")

year_impella_type <- ggplot(data = ecmo_master3, aes(x = year, y = impella_num, fill= impella)) +
    geom_bar(stat="identity")

year_impella_rea <- ggplot(data = ecmo_master3, aes(x = year, y = impella_num, fill= rea)) +
    geom_bar(stat="identity")

graph <- ggarrange(year_ecmo, year_ecmo_type, year_ecmo_rea, year_impella, year_impella_type, year_impella_rea,
                    labels = c("1a. Frequency of ECMOs per hospital site", "1b. Frequency of ECMOs per ECMO type", "1c. Frequency of ECMOs per location of resuscitation",
                               "2a. Frequency of impellas per hospital site", "2b. Frequency of impellas per impella type",
                               "2c. Frequency of impellas per location of resuscitation"),
          ncol = 3, nrow = 2)



#diagnoses

#rename
ecmo_master3 <- rename(ecmo_master3, diag1 = `Diagnose 1 (bitte klar benennnen, noch nicht gruppieren)`)
ecmo_master3 <- rename(ecmo_master3, diag2 = `Diagnose 2`)
ecmo_master3 <- rename(ecmo_master3, diag3 = `Diagnose 3`)
ecmo_master3 <- rename(ecmo_master3, diag4 = `Diagnose 4`)

count(ecmo_master3, diag1)

ecmo_master3 <- ecmo_master3 %>% mutate(shockable = case_when((diag1 == "Kammerflimmern" |
                                                           diag1 == "Ventrikuläre Tachykardie" |
                                                           diag1 == "Pulslose ventrikuläre Tachykardie" |
                                                          diag1 == "Kammerflimmern/ Pulslose elektrische Aktivität" |
                                                            diag1 == "Kammerflimmern bzw. VT" |
                                                            diag1 == "Kammerflimmern und PEA" |
                                                            diag1 == "Kammerflimmern/ PEA" |
                                                            diag1 == "Kammerflimmern/ ventrikuläre Tachykardie" |
                                                            diag1 == "pulslose Ventrikuläre Tachykardie" |
                                                            diag1 == "Pulslose Ventrikuläre Tachykardie" |
                                                            diag1 == "pulslose Ventrikuläre Tachykardie /Kammerflimmern/Asystolie" |
                                                             diag1 == "ventrikuläre Tachykardie" |
                                                             diag1 == "Ventrikuläre Tachykardie/ Kammerflimmern" |
                                                             diag1 == "Ventrikuläre Tachykardien" |
                                                             diag1 == "VF" |
                                                            diag1 == "slow-VT" |
                                                             diag2 == "Pulslose ventrikuläre Tachykardie" |
                                                             diag2 == "Rezidivierende ventrikuläre Tachykardie" |
                                                             diag3 == "Adäquate Schockabgabe des CRT-D bei Ventrikulärer Tachykardie"
                                                          ) ~ 1))
ecmo_master3$shockable[is.na(ecmo_master3$shockable)] <- 0
ecmo_master3$shockable <- as.factor(ecmo_master3$shockable)

ecmo_master3 <- ecmo_master3 %>% mutate(unshockable = case_when((diag1 == "Pulslose elektrische Aktivität" |
                                                           diag1 == "Asystolie" |
                                                             diag1 == "Asystolie unklarer Genese" |
                                                             diag1 == "PEA/Asystolie" |
                                                             diag1 == "	Pulslose Elektrische Aktivität" |
                                                             diag1 == "Pulslose elektrische Aktivität/ Kammerflimmern" |
                                                             diag1 == "Pulslose elektrische Aktivität/ Ventrikuläre Tachykardieo" |
                                                             diag1 == "Pulsloser elektrischer Aktivität"
                                                          ) ~ 1))
ecmo_master3$unshockable[is.na(ecmo_master3$unshockable)] <- 0
ecmo_master3$unshockable <- as.factor(ecmo_master3$unshockable)

ecmo_master3 <- ecmo_master3 %>% mutate(stemi = case_when((diag1 == "STEMI der Vorderwand" |
                                                           diag1 == "STEMI" |
                                                           diag1 == "STEMI der Hinterwand" |
                                                          diag1 == "subakuter STEMI der Vorderwand" |
                                                            diag2 == "STEMI der Vorderwand" |
                                                            diag2== "STEMI" |
                                                            diag2== "STEMI der Hinterwand" |
                                                            diag2 == "STEMI der Seitenwand" |
                                                            diag2 == "subakuter STEMI der Vorderwand" |
                                                            diag2 == "akuter transmuraler Myokardinfarkt" |
                                                            diag2 == "akuter transmuraler Vorderwandinfarkt" |
                                                             diag2 == "inferiorer STEMI" |
                                                             diag2 == "STEMI-Äquivalent bei neu aufgetretenem Linksschenkelblock" |
                                                             diag2 == "STEMI mit Linksschenkelblock" |
                                                             diag2 == "subakuter STEMI" |
                                                            diag3 == "STEMI der Vorderwand" |
                                                             diag3 == "STEMI" |
                                                             diag3 == "STEMI der Hinterwand" |
                                                             diag3 == "subakuter STEMI der Seitenwand" |
                                                            diag3 == "subakuter STEMI der Vorderwand" |
                                                            diag3 == "akuter thrombotischer Verschluss der LCX" |
                                                            diag3 == "akuter transmuraler Hinterwandinfarkt" |
                                                            diag3 == "STEMI bei akut thrombotischem Verschluss der RCA" |
                                                            diag3 == "STEMI bei Hauptstammverschluss" |
                                                            diag3 == "STEMI der Vorderwamd" |
                                                            diag3 == "STEMI der Vorderwand und Seitenwand bei Hauptstammverschluss" |
                                                            diag3 == "STEMI der Vorderwand und Seitwand" |
                                                            diag3 == "STEMI mit Hauptstammverschluss" |
                                                            diag3 == "STEMI Vorderwand" |
                                                            diag3 == "subakuter ST-Hebungsinfarkt der Hinterwand" |
                                                            diag3 == "subakuter STEMI" |
                                                            diag4 == "STEMI" |
                                                            diag4 == "STEMI der Hinterwand"
                                                          ) ~ 1))
ecmo_master3$stemi[is.na(ecmo_master3$stemi)] <- 0
ecmo_master3$stemi <- as.factor(ecmo_master3$stemi)

ecmo_master3 <- ecmo_master3 %>% mutate(nstemi = case_when((diag1 == "NSTEMI" |
                                                              diag2 == "NSTEMI" |
                                                              diag2 == "NSTEMI bei In-Stent-Thrombose" |
                                                              diag3 == "NSTEMI" |
                                                              diag3 == "NSTEMI der Seitenwand" |
                                                              diag3 == "NSTEMI bei HS-Beteiligung" |
                                                              diag3 == "NSTEMI der Vorderwand" |
                                                              diag4 == "NSTEMI"
                                                          ) ~ 1))
ecmo_master3$nstemi[is.na(ecmo_master3$nstemi)] <- 0
ecmo_master3$nstemi <- as.factor(ecmo_master3$nstemi)

ecmo_master3 <- ecmo_master3 %>% mutate(mi = case_when((diag2 == "akuter Myokardinfarkt" |
                                                              diag2 == "Myokardinfarkt" |
                                                              diag2 == "subakuter Myokardinfarkt" |
                                                              diag2 == "subakuter Vorderwandinfarkt" |
                                                              diag2 == "subakuter Vorderwandinnfarkt" |
                                                              diag2 == "unklare AP-Beschwerden" |
                                                              diag2 == "akute myokardiale Ischämie" |
                                                              diag2 == "Stentthrombose RIVA" |
                                                          diag2 == "akute Stentthrombose" |
                                                              diag3 == "Myokardinfarkt" |
                                                              diag3 == "akuter Myokardinfarkt" |
                                                              diag3 == "akuter Myokardinfarkt bei Hauptstammverschluss" |
                                                              diag3 == "akuter Myokardinfarkt der Hinterwand" |
                                                          diag3 == "akuter Vorderwandinfarkt" |
                                                          diag3 == "Hauptstammverschluss" |
                                                          diag3 == "Hauptstammverschluss im Rahmen einer akuten Stentthrombose" |
                                                          diag3 == "Myokardinfarktes" |
                                                          diag3 == "perioperativer Vorderwandinfarkt" |
                                                          diag3 == "Seitenwandinfarkt" |
                                                          diag3 == "subakuter Rechtsherzinfarkt" |
                                                          diag3 == "Typ 2 Myokardinfarkt" |
                                                          diag3 == "Verschluss des Hauptstammes" |
                                                          diag3 == "Vorderwandinfarkt" |
                                                          diag3 == "akute Myokardischämie der Vorderwand" |
                                                          diag3 == "Stentthrombose" |
                                                          diag3 == "Thrombotische Hauptstammstenose" |
                                                          diag3 == "Typ IIa Myokardischämie" |
                                                          diag3 == "akute Verlegung der Koronargefäße" |
                                                          diag3 == "Ischämienachweis im Stressecho" |
                                                          diag4 == "kardiale Ischämie" |
                                                          diag4 == "Instabile Angina pectoris bei Koronarer Dreigefäßerkrankung" |
                                                          diag4 == "Koronare Herzerkrankung mit thrombotischem Verschluss des Hauptstammes/RIVA/RCX"
                                                          ) ~ 1))
ecmo_master3$mi[is.na(ecmo_master3$mi)] <- 0
ecmo_master3$mi <- as.factor(ecmo_master3$mi)

ecmo_master3 <- ecmo_master3 %>% mutate(cs = case_when((diag1 == "kardiogener Schock" |
                                                          diag1 == "kardiogener und septischer Schock" |
                                                          diag1 == "Hypotonie" |
                                                          diag1 == "kardiogener und vasopleger Schock" |
                                                          diag2 == "kardiogener Schock" |
                                                          diag2 == "kardiogener und septischer Schock" |
                                                          diag2 == "kardiogener Schock mit Multiorganversagen" |
                                                          diag3 == "kardiogener Schock" |
                                                           diag4 == "kardiogener Schock" 
                                                          ) ~ 1))
ecmo_master3$cs[is.na(ecmo_master3$cs)] <- 0
ecmo_master3$cs <- as.factor(ecmo_master3$cs)

ecmo_master3 <- ecmo_master3 %>% mutate(lae = case_when((diag2 == "beidseitige Lungenarterienembolie" |
                                                          diag2 == "Lungenarterienembolie" |
                                                           diag2 == "Embolisierung bei Vorhofflimmern" |
                                                           diag2 == "fulminante Lungenarterienembolie beidseits" |
                                                           diag2 == "Lungenarterienembolie links" |
                                                           diag2 == "zentrale Lungenarterienembolie beidseits" |
                                                           diag3 == "Lungenarterienembolie"
                                                          ) ~ 1))
ecmo_master3$lae[is.na(ecmo_master3$lae)] <- 0
ecmo_master3$lae <- as.factor(ecmo_master3$lae)


ecmo_master3 <- ecmo_master3 %>% mutate(pul = case_when((diag1 == "ARDS" |
                                                             diag2 == "pneumogene Sepsis" |
                                                             diag2 == "Pneumonie" |
                                                             diag2 == "Hypoxie" |
                                                             diag2 == "respiratorische Globalinsuffizienz" |
                                                             diag3 == "Pneumonie" |
                                                            diag3 == "Pneumonie und ARDS" |
                                                           diag3 == "Stauungspneumonie" |
                                                            diag3 == "respiratorische Insuffizienz" |
                                                            diag3 == "akute respiratorische Insuffizienz" |
                                                            diag3 == "hypertensives Lungenödem" |
                                                           diag3 == "Lungenödem" |
                                                           diag3 == "Lungenödem"
                                                          ) ~ 1))
ecmo_master3$pul[is.na(ecmo_master3$pul)] <- 0
ecmo_master3$pul <- as.factor(ecmo_master3$pul)


ecmo_master3 <- ecmo_master3 %>% mutate(khk = case_when((diag1 == "koronare Dreigefäßerkrankung" |
                                                           diag2 == "koronare Dreigefäßerkrankung" |
                                                           diag2 == "ischämische Kardiomyopathie" |
                                                           diag2 == "koronare Herzkrankheit" |
                                                           diag2 == "koronare Zweigefäßerkrankung" |
                                                           diag2 == "koronare Eingefäßerkrankung" |
                                                           diag2 == "Hauptstammstenose" |
                                                           diag2 == "koronare Herzerkrankung" |
                                                           diag3 == "koronare Dreigefäßerkrankung" |
                                                           diag3 == "koronare Zweigefäßerkrankung" |
                                                           diag3 == "ischämische Kardiomyopathie" |
                                                           diag3 == "koronare Eingefäßerkrankung" |
                                                           diag3 == "kornare Dreigefäßerkrankung" |
                                                            diag3 == "koronare Dreiefäßerkrankung" |
                                                            diag3 == "koronare Dreigefäßerkankung" |
                                                            diag3 == "KHK" |
                                                            diag3 == "koronare Herzerkrankung" |
                                                           diag4 == "koronare Dreigefäßerkrankung	" |
                                                           diag4 == "koronare Eingefäßerkrankung" |
                                                           diag4 == "koronare Zweigefäßerkrankung" |
                                                           diag4 == "ischämische Kardiomyopathie" |
                                                           diag4 == "KHK" |
                                                           diag4 == "koronare Eingefäßkrankheit" |
                                                           diag4 == "Koronare Zweigefäßerkrankung" |
                                                           diag4 == "subtotale Hauptstammstenose" |
                                                           diag4 == "Instabile Angina pectoris bei Koronarer Dreigefäßerkrankung"
                                                          ) ~ 1))
ecmo_master3$khk[is.na(ecmo_master3$khk)] <- 0


ecmo_master3 <- ecmo_master3 %>% mutate(khk_num = case_when(diag2 == "koronare Eingefäßerkrankung"  | diag3 == "koronare Eingefäßerkrankung" |
                                                              diag4 == "koronare Eingefäßerkrankung" | diag4 == "koronare Eingefäßkrankheit" ~ 1,
                                  diag2 == "koronare Zweigefäßerkrankung" | diag3 == "koronare Zweigefäßerkrankung" | diag4 == "koronare Zweigefäßerkrankung" |
                                     diag4 == "Koronare Zweigefäßerkrankung" ~ 2,
                                  diag1 == "koronare Dreigefäßerkrankung" | diag2 == "koronare Dreigefäßerkrankung" | diag3 == "koronare Dreigefäßerkrankung" |
                                   diag3 == "kornare Dreigefäßerkrankung" |  diag3 == "koronare Dreiefäßerkrankung" | diag3 == "koronare Dreigefäßerkankung" |
                                    diag4 == "koronare Dreigefäßerkrankung" | diag4 == "Instabile Angina pectoris bei Koronarer Dreigefäßerkrankung" ~ 3))
ecmo_master3$khk_num <- as.ordered(ecmo_master3$khk_num)


ecmo_master3 <- ecmo_master3 %>% mutate(sepsis = case_when((diag1 == "Septischer Schock" |
                                                              diag1 == "septischer und kardiogener Schock" |
                                                              diag2 == "septische Kardiomypopathie" |
                                                              diag2 == "septischer Schock" |
                                                              diag3 == "septischer Schock" |
                                                              diag3 == "Toxic Shock Syndrom" |
                                                              diag3 == "V.a. Sepsis bei superinfizierter Stauungsdermatitis" |
                                                              diag3 == "pneumogene Sepsis" |
                                                              diag1 == "pneumogene Sepsis" |
                                                              diag1 == "septischer Schock" |
                                                              diag1 == "Urosepsis"
                                                          ) ~ 1))
ecmo_master3$sepsis[is.na(ecmo_master3$sepsis)] <- 0
ecmo_master3$sepsis <- as.factor(ecmo_master3$sepsis)

ecmo_master3 <- ecmo_master3 %>% mutate(aortdiss = case_when((diag1 == "Aortendissektion Typ A" |
                                                              diag2 == "Typ-A-Dissektion der Aorta ascendens und descendens" |
                                                              diag2 == "Typ A-Dissektion der Aorta"
                                                          ) ~ 1))
ecmo_master3$aortdiss[is.na(ecmo_master3$aortdiss)] <- 0
ecmo_master3$aortdiss <- as.factor(ecmo_master3$aortdiss)

ecmo_master3 <- ecmo_master3 %>% mutate(hi = case_when((diag1 == "akutes Herzversagen" |
                                                          diag1 == "biventrikuläres Herzversagen" |
                                                          diag1 == "Linksherzversagen" |
                                                          diag1 == "Low-Output-Failure" |
                                                          diag1 == "postoperatives myokardiales Pumpversagen" |
                                                          diag1 == "kardiale Dekompensation" |
                                                          diag2 == "kardiale Dekompensation" |
                                                          diag2 == "akute kardiale Dekompensation" |
                                                          diag2 == "low-cardiac-output-Syndrom" |
                                                          diag2== "akute Herzinsuffizienz" |
                                                          diag2 == "biventrikuläres Pumpversagen" |
                                                          diag2 == "Linksherzversagen" |
                                                          diag1 == "low-cardiac-outout-Syndrom" |
                                                          diag1 == "low cardiac output syndrom" |
                                                          diag1 == "Low Output Herzversagen" |
                                                          diag1 == "Rechtsherzversagen" |
                                                          diag3 == "kardiale Dekompensation" |
                                                          diag3 == "rezidivierende kardiale Dekompensation" |
                                                          diag3 == "biventrikuläre Dekompensation" |
                                                          diag3 == "dekompensierte Herzinsuffizienz" |
                                                          diag3 == "Rechtsherzversagen" |
                                                          diag3 == "globale Herzinsuffizienz" |
                                                          diag3 == "HEFrEF" |
                                                          diag3 == "Herzinsuffizienz" |
                                                          diag3 == "Herzinsuffizienz NYHA III-IV" |
                                                          diag3 == "Linksherzversagen" |
                                                          diag3 == "myokardiales Pumpversagen" |
                                                          diag4 == "akutes Linksherzversagen" |
                                                          diag4 == "Rechsherzversagen" |
                                                          diag4 == "kardiale Dekompensation	"
                                                          
                                                          ) ~ 1))
ecmo_master3$hi[is.na(ecmo_master3$hi)] <- 0
ecmo_master3$hi <- as.factor(ecmo_master3$hi)

ecmo_master3 <- ecmo_master3 %>% mutate(myocarditis = case_when((diag1 == "Myokarditis" |
                                                                   diag2 == "akute lymphozytäre Myokarditis" |
                                                                   diag2 == "Eosinophile Myokarditis" |
                                                                   diag2 == "fulminante lymphozytäre Myokarditis" |
                                                                   diag2 == "fulminante Myokarditis" |
                                                                   diag2 == "V.a. Myokarditis" |
                                                                   diag3 == "Myokarditis" |
                                                                   diag4 == "Myokarditis"
                                                          ) ~ 1))
ecmo_master3$myocarditis[is.na(ecmo_master3$myocarditis)] <- 0
ecmo_master3$myocarditis <- as.factor(ecmo_master3$myocarditis)


ecmo_master3 <- ecmo_master3 %>% mutate(intox = case_when((diag2 == "Eiben-Intoxikation" |
                                                             diag2 == "V.a. Intoxikation bei Drogenabusus" |
                                                             diag3 == "Alkoholentzugskrampf" |
                                                             diag3 == "Drogenabusus" |
                                                             diag3 == "Kokainabusus" 
                                                          ) ~ 1))
ecmo_master3$intox[is.na(ecmo_master3$intox)] <- 0
ecmo_master3$intox <- as.factor(ecmo_master3$intox)


#ECG rhythm

year_shockable <- ggplot(data = ecmo_master3, aes(x = year, y = shockable, fill= campus)) +
    geom_bar(stat="identity")

shockable_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = shockable, fill= ecmo)) +
    geom_bar(stat="identity")

shockable_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = shockable, fill= impella)) +
    geom_bar(stat="identity")


year_unshockable <- ggplot(data = ecmo_master3, aes(x = year, y = unshockable, fill= campus)) +
    geom_bar(stat="identity")

unshockable_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = unshockable, fill= ecmo)) +
    geom_bar(stat="identity")

unshockable_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = unshockable, fill= impella)) +
    geom_bar(stat="identity")


#plots

year_stemi <- ggplot(data = ecmo_master3, aes(x = year, y = stemi, fill= campus)) +
    geom_bar(stat="identity")

stemi_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = stemi, fill= ecmo)) +
    geom_bar(stat="identity")

stemi_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = stemi, fill= impella)) +
    geom_bar(stat="identity")



year_nstemi <- ggplot(data = ecmo_master3, aes(x = year, y = nstemi, fill= campus)) +
    geom_bar(stat="identity")

nstemi_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = nstemi, fill= ecmo)) +
    geom_bar(stat="identity")

nstemi_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = nstemi, fill= impella)) +
    geom_bar(stat="identity")


year_mi <- ggplot(data = ecmo_master3, aes(x = year, y = mi, fill= campus)) +
    geom_bar(stat="identity")

mi_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = mi, fill= ecmo)) +
    geom_bar(stat="identity")

mi_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = mi, fill= impella)) +
    geom_bar(stat="identity")


year_cs <- ggplot(data = ecmo_master3, aes(x = year, y = cs, fill= campus)) +
    geom_bar(stat="identity")

cs_ecmo <- ggplot(data = ecmo_master3, aes(x = campus, y = cs, fill= ecmo)) +
    geom_bar(stat="identity")

cs_impella <- ggplot(data = ecmo_master3, aes(x = campus, y = cs, fill= impella)) +
    geom_bar(stat="identity")



year_khk <- ggplot(data = ecmo_master3, aes(x = year, y = khk, fill= khk_num)) +
    geom_bar(stat="identity")

year_lae <- ggplot(data = ecmo_master3, aes(x = year, y = lae, fill= campus)) +
    geom_bar(stat="identity")


year_pul <- ggplot(data = ecmo_master3, aes(x = year, y = pul, fill= campus)) +
    geom_bar(stat="identity")

year_sepsis <- ggplot(data = ecmo_master3, aes(x = year, y = sepsis, fill= campus)) +
    geom_bar(stat="identity")


graph2 <- ggarrange(year_shockable, year_unshockable, year_stemi, year_nstemi, year_mi, year_khk, year_cs, year_lae, year_pul, year_sepsis,
                    labels = c("1a. Frequency of patients with shockable rhythm", "1b. Frequency of patients with unshockable rhythm",
                               "2a. Frequency of patients with STE-ACS", "2b. Frequency of patients with NSTE-ACS",
                               "3a. Frequency of patients with acute myocardial infarction (unspecified)",
                               "3b. Frequency of patients with X-coronary vessel disease",
                    "4a. Frequency of patients with cardiogenic shock",
                    "4b. Frequency of patients with pulmonary embolism",
                    "5a. Frequency of patients with pneumonia, respiratory failure or ARDS",
                    "5b. Frequency of patients with sepsis or septic shock"),
          ncol = 2, nrow = 5)

year_khk <- ggplot(data = ecmo_master3, aes(x = year, y = khk, fill= khk_num)) +
    geom_bar(stat="identity")


#ef

count(ecmo_master3, `LVEF Aufnahme`)

ecmo_master3$ef1 <- as.numeric(ecmo_master3$`LVEF Aufnahme`)
ecmo_master3$ef2 <- as.numeric(ecmo_master3$`LVEF Verlauf/Entlassung`)

bb1 <- ggplot(ecmo_master3, aes(y=ef1)) + 
  geom_boxplot()

bb2 <- ggplot(ecmo_master3, aes(y=ef2)) + 
  geom_boxplot()

bb1_rea <- ggplot(ecmo_master3, aes(y=ef1, color = rea)) + 
  geom_boxplot()

bb2_rea <- ggplot(ecmo_master3, aes(y=ef2, color = rea)) + 
  geom_boxplot()

bb1_stemi <- ggplot(ecmo_master3, aes(y=ef1, color = stemi)) + 
  geom_boxplot()

bb2_stemi <- ggplot(ecmo_master3, aes(y=ef2, color = stemi)) + 
  geom_boxplot()

bb1_nstemi <- ggplot(ecmo_master3, aes(y=ef1, color = nstemi)) + 
  geom_boxplot()

bb2_nstemi <- ggplot(ecmo_master3, aes(y=ef2, color = nstemi)) + 
  geom_boxplot()


graph_ef <- ggarrange(bb1, bb2, bb1_rea, bb2_rea, bb1_stemi, bb2_stemi, bb1_nstemi, bb2_nstemi,
                    labels = c("1a. LVEF at ICU admission", "1b. LVEF at ICU discharge",
                               "2a. LVEF at ICU admission by type of resuscitation", "2b. LVEF at ICU discharge by type of resuscitation",
                               "3a. LVEF at ICU admission in patients with STE-ACS", "3b. LVEF at ICU discharge in patients with STE-ACS",
                               "4a. LVEF at ICU admission in patients with NSTE-ACS", "4b. LVEF at ICU discharge in patients with NSTE-ACS"),
          ncol = 2, nrow = 4)


#provider


#rosc

ecmo_master3 <- rename(ecmo_master3, rosc = `ROSC bei ANSCHLUSS: Ja (1) /nein (0) / keine Reanimation (NA)`)

n <- count(ecmo_master3, rosc)

ecmo_master3 <- ecmo_master3 %>% mutate(rosc_num = case_when(rosc == "NA"  | rosc == "1" | rosc == "1?" | rosc == "1.0" |
                                                     rosc == "(AB klingt wie ROSC, Katheterprotokoll: periterventionelle Reanimation)" ~ "1",
                                                     
                                  rosc == "0" | rosc == "0.0" |
                                  rosc == "0 - primär Anschluss an HLM währen Kreislaufstillstand" | 
                                    rosc == "0 \"Anlage der CARDIOHELP durch Wechsel der arteriellen  Schleuse in der linken Leiste und der venösen Schleuse der rechten Leiste. Dabei Kammerflimmern, welches sich  nicht durch Defibrillation terminieren lässt.. \""  ~ "0",
                                  
                                    rosc == "kein Anschluss" |
                                  rosc == "unklar" | rosc == "?" | rosc == "intermettierende Reanimation" |
                                    rosc == "kein Protokoll" | rosc == "unklar - rezidivierend reanimationspflichtig" |
                                    rosc == "unklar \"bei weiter bestehender rhytmologischer Instabilität Entschluss zur Anlage einer ECMO\"" |
                                    rosc == "unklar \"unter kontinuerlicher Katecholamigabe sowie Impellaimplantation stabilisierten sich die Kreislaufverhältnisse im Verlauf\"" | rosc == "unklar, nach OP Protokoll denke ich 0" ~ "."))

ecmo_master3$rosc_num[ecmo_master3$rea == "No rea"] <- 1 #If no rea happened, then there was ROSC at Anschluss
ecmo_master3$rosc_num[(ecmo_master3$rea == "Out-of-hospital" | ecmo_master3$rea == "In-hospital") & ecmo_master3$rosc == "NA"] <- "."

##check all patients where rosc is NA
rea <- ecmo_master3 %>% select(`Reanimation: out-of-hospital (1) oder in-hospital (2) oder keine Reanimation (0)`, rea, rosc, rosc_num)

ecmo_master3$rosc_num <- as.numeric(ecmo_master3$rosc_num)
ecmo_master3$rosc_num <- as.factor(ecmo_master3$rosc_num)
```

#length of stay (hospital and ICU)

```{r}
##length of stay 
ecmo_master3$admission<- as.Date(ecmo_master3$`Krankenhaus - Aufnahmezeit`)
ecmo_master3$discharge<- as.Date(ecmo_master3$`Krankenhaus - Entlassungszeit`)

ecmo_master3$length_of_stay <-difftime( ecmo_master3$discharge, ecmo_master3$admission, unit="days") 
ecmo_master3$length_of_stay <-as.numeric(ecmo_master3$length_of_stay)

n <-count(ecmo_master3, length_of_stay)
#3 errors in data in negative direction , 1 in positive direction --> have been manually corrected in updated data sheet

#ecmo_master3 <- ecmo_master3 %>% mutate(length_of_stay= replace(length_of_stay,
                                                             # which((length_of_stay<0| length_of_stay>365)), NA))

##ICU length of stay
ecmo_master3$ICU_admission<- as.Date(ecmo_master3$`ITS - Aufnahmezeit`)
ecmo_master3$ICU_discharge<- as.Date(ecmo_master3$`ITS - Entlassungszeit`)

ecmo_master3$ICU_length_of_stay <-difftime( ecmo_master3$ICU_discharge, ecmo_master3$ICU_admission, unit="days") 
ecmo_master3$ICU_length_of_stay <- as.numeric(ecmo_master3$ICU_length_of_stay)

n <-count(ecmo_master3, ICU_length_of_stay)

#ecmo_master3 <- ecmo_master3 %>% mutate(ICU_length_of_stay= replace(ICU_length_of_stay,
                                                               # which((length_of_stay<0| length_of_stay>365)), NA))

#7 errors in data in negative correction, 4 in positive direction --> have been updated manually in corrected data sheet


```

#duration of support systems 
```{r}
#duration of ecmo implantation
ecmo_master3$ecmo_explantation <- as.Date(ecmo_master3$`ECMO wann ausgebaut?`)
ecmo_master3$ecmo_time <- difftime(ecmo_master3$ecmo_explantation, ecmo_master3$ecmo_implantation, unit="days")
ecmo_master3$ecmo_time <- as.numeric(ecmo_master3$ecmo_time)
n <- count(ecmo_master3, ecmo_time)
#errors have been identified and corrected manually on updated spreadsheet 

#duration of impella implantation
ecmo_master3$impella_explantation <- as.Date(ecmo_master3$`Impella wann ausgebaut?`)
ecmo_master3$impella_time <- difftime(ecmo_master3$impella_explantation, ecmo_master3$impella_implantation, unit="days")
ecmo_master3$impella_time <- as.numeric(ecmo_master3$impella_time)
n <- count(ecmo_master3, impella_time)
#errors have been identified and corrected manually on updated spreadsheet 


mean(ecmo_master3$impella_time, na.rm=T)
mean(ecmo_master3$ecmo_time, na.rm=T)


```

#Megans graphs
```{r}

intervention <- ggplot(ecmo_master7, aes(x="", y= "", fill=intervention)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()
intervention


ecmella <- ecmo_master7 %>% filter(intervention=="ECMELLA")
rea_ec <- ggplot(ecmella, aes(x="", y= "", fill=rea)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()
rea_ec

ecmo <- ecmo_master7 %>% filter(intervention=="VA-ECMO")
rea_ecmo <- ggplot(ecmo, aes(x="", y= "", fill=rea)) +
  geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0) +
  theme_void()
rea_ecmo


los <-ggplot(ecmo_master7, 
       aes(x = length_of_stay2, 
           y = intervention, 
           fill = intervention)) +
  geom_density_ridges() + 
  theme_ridges() +
  theme(legend.position = "none")

ecmo_master3$mort_num <- ifelse(ecmo_master3$mort==T, 1, 0)

table <- ecmo_master7 %>%
  group_by(intervention) %>%
  summarise(
    len = mean(length_of_stay2, na.rm=T)
  )
# Initialize ggplot with data
los2 <- ggplot(
  table, aes(x = intervention, y = len)) +
  geom_bar(stat = "identity",  fill = c("cornflowerblue", "chartreuse3")) +
  labs(title = "Mean Hospital Length of Stay", 
       x = "intervention",
       y = "Length of Stay in Days")
los2


table2 <- ecmo_master7 %>%
  group_by(intervention) %>%
  summarise(
    len = mean(ICU_length_of_stay2, na.rm=T)
  )
# Initialize ggplot with data
g <- ggplot(
  table2, aes(x = intervention, y = len)) +
  geom_bar(stat = "identity",  fill = c("cornflowerblue", "chartreuse3")) +
  labs(title = "Mean Length of Stay in ICU", 
       x = "intervention",
       y = "Length of Stay in ICU in Days")
g

```


```{r}
#create final cohort

##ecmo_master3_1 <- ecmo_master3 %>% filter(rea == "In-hospital" | rea == "Out-of-hospital") #cardiac arrest
##ecmo_master3_2 <- ecmo_master3_1 %>% filter(rosc_num == 0) #ROSC at implantation
##ecmo_master3_3 <- ecmo_master3_2 %>% filter(trt == 1 | trt == 0) #ECMO or ECMELLA

ecmo_master4 <- ecmo_master3 %>% filter(rosc_num == 0 &  (rea == "In-hospital" | rea == "Out-of-hospital") & (trt == 1 | trt == 0))



#create infarct (yes/no) variable manually by looking at diag1 - diag4
#create diag5 (based on chart review if diag1 - diag4 were not enough to define infarct variable)

primdiag <- ecmo_master4 %>% select(id, Fallnumer, trt, mort, diag1, diag2, diag3, diag4) %>% filter(trt == 0 & mort == "FALSE")

##create excel sheets for manual edit

library("writexl")
write_xlsx(primdiag,"E:/backup9/projects/ecmella_outcomes/kenny/data/data3/ECMO_outcomes/primdiag/trt1mort1.xlsx")
write_xlsx(primdiag,"E:/backup9/projects/ecmella_outcomes/kenny/data/data3/ECMO_outcomes/primdiag/trt1mort0.xlsx")
write_xlsx(primdiag,"E:/backup9/projects/ecmella_outcomes/kenny/data/data3/ECMO_outcomes/primdiag/trt0mort1.xlsx")
write_xlsx(primdiag,"E:/backup9/projects/ecmella_outcomes/kenny/data/data3/ECMO_outcomes/primdiag/trt0mort0.xlsx")

##import all sheets - make infarct variable numeric

library(readxl)
trt1mort1_c <- read_excel("primdiag/trt1mort1_c.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text"))

library(readxl)
trt1mort0_c <- read_excel("primdiag/trt1mort0_c.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text"))

library(readxl)
trt0mort1_c <- read_excel("primdiag/trt0mort1_c.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text"))

library(readxl)
trt0mort0_c <- read_excel("primdiag/trt0mort0_c.xlsx", 
    col_types = c("numeric", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text"))

##append all sheets
manual_infarct <- rbind(trt1mort1_c, trt1mort0_c, trt0mort1_c, trt0mort0_c)
manual_infarct <- manual_infarct %>% select(id, infarct, diag5) #clean


##merge with main dataset
ecmo_master5 <- merge(ecmo_master4, manual_infarct, by= "id")

ecmo_master6 <- ecmo_master5 %>% filter(infarct == 1)


#create clean dataset for tables
summary <- ecmo_master6 %>% select(id, Fallnumer, trt, campus, year, diag1, diag2, diag3, diag4, infarct, shockable, unshockable, stemi, nstemi, mi, cs, khk, khk_num, aortdiss, hi, myocarditis, lae, pul, sepsis, intox, mort, rosc_num, rea, length_of_stay, ICU_length_of_stay,  ecmo_time, impella_time, ef1, ef2)


#table1
library(table1)

##label variables

summary$trt <- factor(summary$trt , levels=c("0", "1"), labels=c("VA-ECMO", "ECMELLA"))
label(summary$trt) <- "Type of MCS"

summary$campus <- factor(summary$campus , levels=c("cbf", "ccm", "cvk"), labels=c("CBF", "CCM", "CVK"))
label(summary$campus) <- "Hospital site"

label(summary$year) <- "Years of MCS implantation"

summary$shockable <- factor(summary$shockable , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$shockable) <- "Shockable ECG rhythm"

summary$unshockable <- factor(summary$unshockable , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$unshockable) <- "Unshockable ECG rhythm"

summary$infarct <- factor(summary$infarct , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$infarct) <- "Myocardial infarction as reason for MCS"


summary$stemi <- factor(summary$stemi , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$stemi) <- "STE-ACS"

summary$nstemi <- factor(summary$nstemi , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$nstemi) <- "NSTE-ACS"

summary$mi <- factor(summary$mi , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$mi) <- "Myocardial infarction (not further specified)"

summary$cs <- factor(summary$cs , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$cs) <- "Cardiogenic shock"

summary$khk_num <- factor(summary$khk_num , levels=c("1", "2", "3"), labels=c("1 vessel", "2 vessels", "3 vessels"))
label(summary$khk_num) <- "Coronary artery disease"

summary$aortdiss <- factor(summary$aortdiss , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$aortdiss) <- "Aortic dissection"

summary$hi <- factor(summary$hi , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$hi) <- "Heart failure"

summary$mocarditis <- factor(summary$myocarditis , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$myocarditis) <- "Myocarditis"

summary$lae <- factor(summary$lae , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$lae) <- "Pulmonary embolism"

summary$pul <- factor(summary$pul, levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$pul) <- "Pneumonia, respiratory failure or ARDS"

summary$sepsis <- factor(summary$sepsis , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$sepsis) <- "Septic shock"

summary$rosc_num <- factor(summary$rosc_num , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$rosc_num) <- "ROSC at implantantion of MCS device"

summary$intox <- factor(summary$intox , levels=c("0", "1"), labels=c("No", "Yes"))
label(summary$intox) <- "Drug intoxication"

label(summary$rea) <- "Location of resuscitation"

label(summary$mort) <- "Hospital mortality"

label(summary$length_of_stay) <- "Hospital length of stay (days)"
label(summary$ICU_length_of_stay) <- "ICU length of stay (days)"
label(summary$ecmo_time) <- "Duration of VA-ECMO (days)"
label(summary$impella_time) <- "Duration of Impella (days)"

label(summary$ef1) <- "Left ventricular EF at ICU admission"
label(summary$ef2) <- "Left ventricular EF at ICU discharge"

##create table
ecmo_master4_table1 <-  table1(~ campus + rosc_num + infarct + rea +
                                 mort +  length_of_stay + ICU_length_of_stay + ecmo_time + impella_time + ef1 + ef2 +
                                 stemi+ nstemi+ mi+ cs+ khk_num + shockable+ unshockable | trt,
                               data= summary)

ecmo_master4_table2 <-  table1(~ unshockable+ infarct + rosc_num +  rea +
                                 mort +  length_of_stay + ICU_length_of_stay + ecmo_time + impella_time + ef1 + ef2 +
                                 stemi+ nstemi+ mi+ cs+ khk_num+ aortdiss+ hi+ myocarditis+ lae+ pul+ sepsis+ intox | trt*campus,
                               data= summary)

ecmo_master4_table3 <-  table1(~ campus + shockable+ infarct + unshockable+ rosc_num +  rea +
                                length_of_stay + ICU_length_of_stay + ecmo_time + impella_time + ef1 + ef2 +
                                 stemi+ nstemi+ mi+ cs+ khk_num+ aortdiss+ hi+ myocarditis+ lae+ pul+ sepsis+ intox | trt*mort,
                               data= summary)

xtabs(~campus+trt,data= summary)






log_mort <- glm(mort ~ trt,
          data = ecmo_master7, family = "binomial")
summary(log_mort)
exp(cbind(OR = coef(log_mort), confint(log_mort)))


library(MASS)

los <- glm(length_of_stay ~ trt,  family = poisson, data = ecmo_master6)
summary(los)
exp(cbind(IRR = coef(los), confint(los)))


iculos <- glm(ICU_length_of_stay ~ trt,  family = poisson, data = ecmo_master6)
summary(iculos)
exp(cbind(IRR = coef(iculos), confint(iculos)))

#resuts table
library(jtools)
library(huxtable)
library(officer)
library(flextable)

res_mort <- summ(log_mort, exp = TRUE, confint = TRUE, digits = 3, scale = TRUE)
res_los <- summ(los, exp = TRUE, confint = TRUE, digits = 3, scale = TRUE)
res_iculos <- summ(iculos, exp = TRUE, confint = TRUE, digits = 3, scale = TRUE)

export_summs(log_mort, los, iculos, exp = TRUE, digits = 3,  error_format = "[{conf.low}, {conf.high}]", scale = TRUE, to.file = "docx", file.name = "primaryoutcomes.docx")
```

#Provider variable
```{r}
#import data
library(readxl)
id_provider <- read_excel("E:/backup9/projects/ecmella_outcomes/kenny/data/data3/additional_data/provider/id_provider.xlsx")
View(id_provider)

##clean dataset
id_provider2 <- id_provider %>% select(id, prov1_t1, prov2_t1, prov3_t1, prov1_t2, prov2_t2, prov3_t3)

#merge with master datatset
ecmo_master7 <- merge(ecmo_master6, id_provider2, by= "id")
ecmo_master7$prov1_t1 <- as.ordered(ecmo_master7$prov1_t1)
ecmo_master7$prov1_t1_num <- as.numeric(ecmo_master7$prov1_t1)

n <- count(ecmo_master7,prov1_t1)

graph_prov <- ggplot(ecmo_master7, aes(y=trt, color = prov1_t1_num)) + 
  geom_boxplot()

hist_prov <-ggplot(ecmo_master7, aes(x= prov1_t1_num, fill = campus, color = campus)) + 
    geom_histogram( alpha=0.5, position="identity") +
   labs(title="Frequency of MCS implantation as part of eCPR by primary provider ID (\"Untersucher 1\") and hospital site",x="Provider ID", y = "Count") +
  theme_classic()
```



additional chart review
```{r}
#import data
library(readxl)
new_chart <- read_excel("~/Uni/Promotion/ECMELLA/chart review/new_chart.xlsx", 
    col_types = c("numeric", "numeric", "text", 
        "text", "date", "date", "date", "date", 
        "date"))
View(new_chart)


#merge new data frame with existing
ecmo_master7 <- merge(ecmo_master6, new_chart[, c(1,3,4,5,6,7,8,9)], by="id", all=T)
#campus2 is new variable containing campus for ALL patients
#cad is new variable containing information on coronary artery disease on ALL patients

#control 
n <- ecmo_master7 %>% select(id, admission, admission2)

n <- ecmo_master7 %>% select(id, ICU_admission, ICU_admission2)

n <- ecmo_master7 %>% select(id, ICU_discharge, ICU_discharge2)

n <- ecmo_master7 %>% select(id, ecmo_ex, ecmo_explantation)

n <- ecmo_master7 %>% select(id, impella_ex, impella_explantation)

#new length of stay
ecmo_master7$length_of_stay2 <-difftime( ecmo_master7$discharge, ecmo_master7$admission2, unit="days") 
ecmo_master7$length_of_stay2 <-as.numeric(ecmo_master7$length_of_stay2)

n <-count(ecmo_master7, length_of_stay2)
 
#new ICU length of stay
ecmo_master7$ICU_length_of_stay2 <-difftime( ecmo_master7$ICU_discharge2, ecmo_master7$ICU_admission2, unit="days")
ecmo_master7$ICU_length_of_stay2 <- as.numeric(ecmo_master7$ICU_length_of_stay2)

n <-count(ecmo_master7, ICU_length_of_stay2)


#new ecmo time
ecmo_master7$ecmo_time2 <- difftime(ecmo_master7$ecmo_ex, ecmo_master7$ecmo_implantation, unit="days")
ecmo_master7$ecmo_time2 <- as.numeric(ecmo_master7$ecmo_time2)
n <- count(ecmo_master7, ecmo_time2)

#new impella time
ecmo_master7$impella_time2 <- difftime(ecmo_master7$impella_ex, ecmo_master7$impella_implantation, unit="days")
ecmo_master7$impella_time2 <- as.numeric(ecmo_master7$impella_time2)
n <- count(ecmo_master7, impella_time2)

#new tables
ecmo_master7_table1 <-  table1(~ campus2 + rea + mort + length_of_stay2 + ICU_length_of_stay2 + ecmo_time2 + impella_time2 +
                                cad + shockable +unshockable + ef1 + ef2| trt, data= ecmo_master7)









#cause of death 
#import additional Chart Review
library(readxl)
cod <- read_excel("~/Uni/Promotion/ECMELLA/chart review/cod2.xlsx", 
    col_types = c("numeric", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "text"))
View(cod)

cod <- rename(cod, cod4 ='...6')
cod[,9]<- list(NULL)

n <- count(cod, cod1)
n2 <- count(cod, cod2)
n3 <- count(cod, cod3)
n4 <- count(cod, cod4)

cod <- cod %>% mutate(hypox_brain = case_when((cod1 == "schwerer hypoxischer Hirnschaden" |
                                               cod1 == "Hirntod" |
                                               cod1 == "posthypoxische Enzephalopathie" |
                                               cod1 == "mind. mittelgradig hypoxischer Hirnschaden" |
                                               cod2 == "hypoxischer Hirnschaden" |
                                               cod2 == "posthypoxische Enzephalopathie" |
                                               cod2 == "schwerer hypoxischer Hirnschaden" |
                                              cod2 == "V.a. schweren hypoxischen Hirnschaden") ~ 1))
cod$hypox_brain[is.na(cod$hypox_brain)] <- 0
cod$hypox_brain <- as.factor(cod$hypox_brain)


cod <- cod %>% mutate(mof = case_when((cod1 == "Multiorganversagen" |
                                               cod1 == "therapierefraktäres Multiorganversagen" |
                                               cod2 == "Multiorganversagen" |
                                               cod3 == "Multiorganversagen" |
                                               cod4 == "Multiorganversagen") ~ 1))
cod$mof[is.na(cod$mof)] <- 0
cod$mof <- as.factor(cod$mof)


cod <- cod %>% mutate(infect.inflam = case_when((cod2 == "septischer  und kardiogener Schock" |
                                                  cod2 == "SIRS"|
                                               cod2 == "septischer Schock" |
                                               cod2 == "septischer und kardiogener Schock" |
                                               cod3 == "Sepsis" |
                                               cod3 == "pneumogene Sepsis" |
                                               cod3 == "Pneumonie" |
                                               cod3 == "Peritonitis mit akutem Abdomen" |
                                              cod3 == "Covid-Pneumonie") ~ 1))
cod$infect.inflam[is.na(cod$infect.inflam)] <- 0
cod$infect.inflam <- as.factor(cod$infect.inflam)


cod <- cod %>% mutate(bleed = case_when((cod1 == "hämorrhagischer Schock" |
                                                  cod1 == "Hämorrhagischer Schock"|
                                               cod2 == "Blutung" |
                                               cod2 == "Koagulopathie" |
                                               cod2 == "perioperative Blutung" |
                                               cod2 == "pulmonale Hämorrhagie" |
                                               cod3 == "Gerinnungsstörrung" |
                                               cod3 == "Hämolyse" |
                                               cod3 == "Koagulopathie" |
                                              cod3 == "Hämolyse bei ECMO"|
                                              cod4=="septische Koagulopathie und HIT II") ~ 1))
cod$bleed[is.na(cod$bleed)] <- 0
cod$bleed <- as.factor(cod$bleed)


cod <- cod %>% mutate(cardiogenic_shock = case_when((cod1 == "kardiogener Schock" |
                                                  cod1 == "therapierefraktärer kardiogener Schock"|
                                               cod2 == "kardiogener Schock" |
                                               cod2 == "septischer  und kardiogener Schock" |
                                               cod2 == "septischer und kardiogener Schock" |
                                               cod2 == "protrahierter kardiogener Schock") ~ 1))
cod$cardiogenic_shock[is.na(cod$cardiogenic_shock)] <- 0

ecmomaster8 <- merge(ecmo_master7, cod[, c(1,3,4,5,6,7,8,9,10,11,12,13)], by="id", all=T)
table_death <- ecmomaster8 %>% filter(!cod1=="0.0")

table1_death <- table1(~hypox_brain + mof + infect.inflam +bleed + cardiogenic_shock|intervention, data=table_death)

```



#cause of death
```{r}
#cause of death 
#import additional Chart Review
library(readxl)
cod <- read_excel("~/Uni/Promotion/ECMELLA/chart review/cod2.xlsx", 
    col_types = c("numeric", "text", "text", 
        "text", "text", "text", "numeric", 
        "numeric", "text"))
View(cod)

cod <- rename(cod, cod4 ='...6')
cod[,9]<- list(NULL)

n <- count(cod, cod1)
n2 <- count(cod, cod2)
n3 <- count(cod, cod3)
n4 <- count(cod, cod4)

cod <- cod %>% mutate(hypox_brain = case_when((cod1 == "schwerer hypoxischer Hirnschaden" |
                                               cod1 == "Hirntod" |
                                               cod1 == "posthypoxische Enzephalopathie" |
                                               cod1 == "mind. mittelgradig hypoxischer Hirnschaden" |
                                               cod2 == "hypoxischer Hirnschaden" |
                                               cod2 == "posthypoxische Enzephalopathie" |
                                               cod2 == "schwerer hypoxischer Hirnschaden" |
                                              cod2 == "V.a. schweren hypoxischen Hirnschaden") ~ 1))
cod$hypox_brain[is.na(cod$hypox_brain)] <- 0
cod$hypox_brain <- as.factor(cod$hypox_brain)


cod <- cod %>% mutate(mof = case_when((cod1 == "Multiorganversagen" |
                                               cod1 == "therapierefraktäres Multiorganversagen" |
                                               cod2 == "Multiorganversagen" |
                                               cod3 == "Multiorganversagen" |
                                               cod4 == "Multiorganversagen") ~ 1))
cod$mof[is.na(cod$mof)] <- 0
cod$mof <- as.factor(cod$mof)


cod <- cod %>% mutate(infect.inflam = case_when((cod2 == "septischer  und kardiogener Schock" |
                                                  cod2 == "SIRS"|
                                               cod2 == "septischer Schock" |
                                               cod2 == "septischer und kardiogener Schock" |
                                               cod3 == "Sepsis" |
                                               cod3 == "pneumogene Sepsis" |
                                               cod3 == "Pneumonie" |
                                               cod3 == "Peritonitis mit akutem Abdomen" |
                                              cod3 == "Covid-Pneumonie") ~ 1))
cod$infect.inflam[is.na(cod$infect.inflam)] <- 0
cod$infect.inflam <- as.factor(cod$infect.inflam)


cod <- cod %>% mutate(bleed = case_when((cod1 == "hämorrhagischer Schock" |
                                                  cod1 == "Hämorrhagischer Schock"|
                                               cod2 == "Blutung" |
                                               cod2 == "Koagulopathie" |
                                               cod2 == "perioperative Blutung" |
                                               cod2 == "pulmonale Hämorrhagie" |
                                               cod3 == "Gerinnungsstörrung" |
                                               cod3 == "Hämolyse" |
                                               cod3 == "Koagulopathie" |
                                              cod3 == "Hämolyse bei ECMO"|
                                              cod4=="septische Koagulopathie und HIT II") ~ 1))
cod$bleed[is.na(cod$bleed)] <- 0
cod$bleed <- as.factor(cod$bleed)


cod <- cod %>% mutate(cardiogenic_shock = case_when((cod1 == "kardiogener Schock" |
                                                  cod1 == "therapierefraktärer kardiogener Schock"|
                                               cod2 == "kardiogener Schock" |
                                               cod2 == "septischer  und kardiogener Schock" |
                                               cod2 == "septischer und kardiogener Schock" |
                                               cod2 == "protrahierter kardiogener Schock") ~ 1))
cod$cardiogenic_shock[is.na(cod$cardiogenic_shock)] <- 0
cod$cardiogenic_shock <- as.factor(cod$cardiogenic_shock)


ecmomaster8 <- merge(ecmo_master7, cod[, c(1,3,4,5,6,7,8,9,10,11,12,13)], by="id", all=T)
table_death <- ecmomaster8 %>% filter(!cod1=="0.0")

table1_death <- table1(~hypox_brain + mof + infect.inflam +bleed + cardiogenic_shock|intervention, data=table_death)

```



Decision Tree
```{r}
#Decision Tree

install.packages("FSelector")
install.packages("rpart")
 install.packages("caret")
install.packages("rpart.plot")
install.packages("data.tree")
install.packages("caTools")
install.packages("ElemStatLearn")


library(FSelector)
library(rpart)
library(caret)
library(rpart.plot)
library(data.tree)
library(caTools)
library(ElemStatLearn)

#selecting only meaningful columns for prediction 

df <- ecmo_master7 %>% select(mort, trt, shockable)
df$mort <- as.factor(df$mort)
df$cad <- as.ordered(df$cad)
set.seed(123)
sample = sample.split(df$mort, SplitRatio=.60)
train= subset(df, sample==TRUE)
test = subset(df, sample==FALSE)

tree <- rpart(mort ~., data=train)


tree.survived.predicted <- predict(tree, test, type="class")
confusionMatrix(tree.survived.predicted, test$mort)

prp(tree)
```

Find new case numbers in Kalinowsky new data
```{r}
#just checking we do not accidentally miss patients

#import new table 
library(readxl)
new_data_K <- read_excel("~/Uni/Promotion/ECMELLA/chart review/new_data_K.xlsx", 
    col_types = c("text", "text", "text", 
        "date", "text", "text"))
View(new_data_K)

#ecmo_master1 is data set in which all case numbers of reviewed patients are in 
#create sub data set with only case numbers of this one and create new variable "done" to identify all reviewed patients in later merge

em1 <- ecmo_master1 %>% select("Fallnumer")
em1$done <-1

#merge together
new_data <- merge(em1, new_data_K, by.x="Fallnumer", by.y="Fallnummer", all=T)

count(new_data, done)
#apparently 18 new case_numbers that haven't been reviewed yet, all of them  after 27.04.21
#1 case has already been reviewed but had additional procedure -> review as well

new_data2 <- new_data %>% filter(is.na(done)| (Untersuchungsnummer =="21-HYHK-00362" ))

#save data and import on excel sheet
write_xlsx(new_data2,"C:/Users/HP-EliteBook-840-G3/Desktop/new_data2.xlsx")

#manually added to drive spreadseet

```

#EF values

```{r}
library(readxl)
id_ef_cod <- read_excel("E:/backup9/projects/ecmella_outcomes/kenny/data/data3/additional_data/ef_cod/id_ef_cod.xlsx")
View(id_ef_cod)

#create dataframe only with EF variables and cod
id_ef_cod2 <- id_ef_cod %>% select(id, cod_main, ef_admission, ef_discharge)

#make EF variables numeric
id_ef_cod2$ef_admission2 <- as.numeric(id_ef_cod2$ef_admission)
id_ef_cod2$ef_discharge2 <- as.numeric(id_ef_cod2$ef_discharge)

#merge variables with main dataset
ecmo_master7 <- merge(ecmo_master7, id_ef_cod2, by= "id")

#create final EF variables
ecmo_master7$trt2 <- as.factor(ecmo_master7$trt) #make trt factorial

ef_bp0 <- ggplot(ecmo_master7, aes(x=trt2, y=ef_admission2, fill=trt2)) + 
    geom_boxplot() + ylim(0, 60) +
  labs(title = "LVEF at ICU admission", 
       x = "va-ECMO vs. ECMELLA",
       y = "LVEF (percent)")

ef_bp1 <- ggplot(ecmo_master7, aes(x=trt2, y=ef_discharge2, fill=trt2)) + 
    geom_boxplot()+  ylim(0, 60) +
  labs(title = "LVEF at ICU discharge", 
       x = "va-ECMO vs. ECMELLA",
       y = "LVEF (percent)")

eff_bp_all <- ggarrange(ef_bp0, ef_bp1,
          ncol = 1, nrow = 2)

#t test
t.test(ef_admission2 ~ trt, data = ecmo_master7)
t.test(ef_discharge2 ~ trt, data = ecmo_master7)

#create difference between admission and discharge
ecmo_master7 <- ecmo_master7 %>% mutate(ef_diff = ef_discharge2 - ef_admission2 )
t.test(ef_diff ~ trt, data = ecmo_master7)
```


#mortality - Kaplan Meier curve

```{r}
ecmo_master7$survdays <-difftime(ecmo_master7$`Sterbezeit (0 = nicht tot)`, ecmo_master7$ecmo_implantation, unit="days")
ecmo_master7$survdays <- as.numeric(ecmo_master7$survdays)

ecmo_master7 <- ecmo_master7 %>% mutate(survdays= replace(survdays, which((survdays<0)), 50)) #survived patients = 50 days

survdays_check <- ecmo_master7 %>% select(ecmo_implantation, `Sterbezeit (0 = nicht tot)`, survdays) #check

library(survival)
library(ggfortify)
km <- with(ecmo_master7, Surv(survdays))
km_trt_fit <- survfit(Surv(survdays) ~ trt, data=ecmo_master7)
autoplot(km_trt_fit)

library("survminer")
fit <- survfit(Surv(survdays) ~ trt, data = ecmo_master7)
surv <- ggsurvplot(fit, data = ecmo_master7, pval = TRUE, risk.table = TRUE, risk.table.col = "strata",
                   legend.labs = c("VA-ECMO", "ECMELLA"), ggtheme = theme_bw(),
                   xlim = c(0,45), xlab = "Time in days", ylab = "Survical probability")
```


```{r}
#check data
ecmo_master3_check <- ecmo_master3 %>% filter(rosc_num == 1 &  mort == FALSE & (rea == "In-hospital" | rea == "Out-of-hospital") & (trt == 1))

ecmo_master3_check <- ecmo_master3_check %>% select(Fallnumer, Patientenummer, rea, rosc, rosc_num, mort, trt, ecmo, impella)
```
